import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

/**
 * Small key/value store for licences.
 *
 * On Netlify this is the Blob store. Running `astro dev` on its own has no Blobs context, so
 * it falls back to JSON files under .kakas-dev-data/ - that keeps the whole purchase and
 * unlock flow testable locally without needing `netlify dev`.
 */
export interface KeyValueStore {
    get<T>(key: string): Promise<T | null>;
    set(key: string, value: unknown): Promise<void>;
    remove(key: string): Promise<void>;
    /** True when writes survive a restart and are shared between instances. */
    readonly durable: boolean;
}

const LOCAL_DIR = '.kakas-dev-data';

function localPath(name: string, key: string): string {
    // Keys are generated by us (licence keys, session ids) but never trust them with paths.
    const safe = key.replace(/[^A-Za-z0-9_-]/g, '_');
    return join(process.cwd(), LOCAL_DIR, name, `${safe}.json`);
}

function fileStore(name: string): KeyValueStore {
    return {
        durable: false,
        async get<T>(key: string): Promise<T | null> {
            try {
                return JSON.parse(await readFile(localPath(name, key), 'utf8')) as T;
            } catch {
                return null;
            }
        },
        async set(key: string, value: unknown): Promise<void> {
            const path = localPath(name, key);
            await mkdir(dirname(path), { recursive: true });
            await writeFile(path, JSON.stringify(value, null, 2), 'utf8');
        },
        async remove(key: string): Promise<void> {
            try {
                await unlink(localPath(name, key));
            } catch {
                // Already gone.
            }
        }
    };
}

const stores = new Map<string, KeyValueStore>();

export async function getStore(name: string): Promise<KeyValueStore> {
    const cached = stores.get(name);
    if (cached) return cached;

    let store: KeyValueStore;
    try {
        const { getStore: getBlobStore } = await import('@netlify/blobs');
        // Strong consistency matters here: a licence must be readable the instant it is
        // written, because the customer is redirected straight to the page that reads it.
        const blobs = getBlobStore({ name, consistency: 'strong' });
        // getStore is lazy, so make one call to confirm the environment is really wired up.
        await blobs.get('__probe');
        store = {
            durable: true,
            async get<T>(key: string): Promise<T | null> {
                return ((await blobs.get(key, { type: 'json' })) as T) ?? null;
            },
            async set(key: string, value: unknown): Promise<void> {
                await blobs.setJSON(key, value);
            },
            async remove(key: string): Promise<void> {
                await blobs.delete(key);
            }
        };
    } catch {
        store = fileStore(name);
    }

    stores.set(name, store);
    return store;
}
